version: 2

sources:
  - name: raw # Renaming as an alias
    schema: gz_raw_data # Path of the dataset in BQ
    description: greenwez raw data source # optional
    tables:
      - name: sales # Renaming as an alias
        identifier: raw_gz_sales # Exact name of the table in BQ
        description: sales of greenweez / we have one row per product_id found in each order_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
       
      - name: product # Renaming as an alias
        identifier: raw_gz_product # Exact name of the table in BQ
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
            - unique
            - not_null          

      - name: ship # Renaming as an alias
        identifier: raw_gz_ship # Exact name of the table in BQ
        description: order shipping price by orders_id
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
